<?php include "includes/header.php" ?>
<h1>My First PHP Document</h1>
<?php

echo "<h3>here is my first line of code generated by php</h3>";
echo "here is another line of code";

echo "<p>This could be used to do some <span class=\"hilite\"> sylish HTML stuff<span/></p>";
?>
<?php include "includes/footer.php" ?>