// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindSystem.Entities
{
    [Index("CustomerID", Name = "CustomerID")]
    [Index("CustomerID", Name = "CustomersOrders")]
    [Index("SalesRepID", Name = "EmployeeID")]
    [Index("SalesRepID", Name = "EmployeesOrders")]
    [Index("OrderDate", Name = "OrderDate")]
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public int OrderID { get; set; }
        public int? SalesRepID { get; set; }
        [Required]
        [StringLength(5)]
        public string CustomerID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequiredDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PaymentDueDate { get; set; }
        [Column(TypeName = "money")]
        public decimal? Freight { get; set; }
        public bool Shipped { get; set; }
        [StringLength(40)]
        public string ShipName { get; set; }
        public int? ShipAddressID { get; set; }
        [StringLength(250)]
        public string Comments { get; set; }

        [InverseProperty("Order")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}